/*
 * Generated by MTK SP DrvGen Version 03.13.1  for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Thu Jul  4 21:45:59 2013
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1




#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD1_CNT      0


