/*
 * Generated by MTK SP DrvGen Version 03.13.1  for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Thu Jul  4 21:45:59 2013
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_MSDC1     GPIO_VMC
#define GPIO_DVDD28_MSDC2     GPIO_VIO18
#define GPIO_DVDD28_BPI     GPIO_VIO18


